file_ops:
  base_dir: "./data"

vector_ops:
  index_path: "./faiss_index"
  model_name: "sentence-transformers/all-mpnet-base-v2"

llm_ops:
  model_name: "llama3.2:1b"
  temperature: 0.5
  max_tokens: 1000
  top_p: 0.9
  top_k: 50
  frequency_penalty: 0
  presence_penalty: 0
